server:
  port: 8080
  readTimeout: "10s"
  writeTimeout: "10s"
  idleTimeout: "60s"
  enableLogging: true

security:
  enableBasicAuth: true
  basicAuthUsers:
    alice: password123
    bob: secret456

plugins:
  openapi:
    enabled: false
    spec_path: "./openapi.yaml"
    path: "/openapi"         # Optional, default: /openapi
    format: "json"           # Optional, "yaml" or "json" (default: yaml)
    swagger_ui: false          # Optional, serve Swagger UI at /swagger-ui/