# config.yaml - Main API Gateway Configuration File

plugins:
  storage:
    type: "etcd"
    endpoints:
      - "localhost:2379"
    timeout: 5s
    prefix: "/iket"

  auth:
    type: "saml"
    entity_id: "http://localhost:8080/saml/metadata"
    assertion_url: "http://localhost:8080/saml/acs"
    metadata_url: "http://localhost:8080/saml/metadata"
    session_max_age: 3600
    key_file: "/app/certs/server.key"
    cert_file: "/app/certs/server.crt"
server:
  port: 8080
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 120s
  pluginsDir: "/app/plugins"
  enableLogging: true
  basicAuthUsers:
    admin: "$2a$10$N9qo8uLOickgx2ZMRZoMy.Mrq4H3.HoAZZoLsL/4ZDFBH7/4X.1Oa"  # bcrypt hashed password
    user1: "$2a$10$N9qo8uLOickgx2ZMRZoMy.Mrq4H3.HoAZZoLsL/4ZDFBH7/4X.1Oa"


# 'http://localhost:8180/realms/kychat/protocol/openid-connect/token' \

security:
  # TLS Configuration
  tls:
    enabled: true
    cert_file: "/app/certs/server.crt"
    key_file: "/app/certs/server.key"
    min_version: "TLS1.2"
    ciphers:
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

  # HTTP Security Headers
  headers:
    X-Frame-Options: "DENY"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"
    Content-Security-Policy: "default-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    Referrer-Policy: "strict-origin-when-cross-origin"

  # Rate Limiting
  rate_limit:
    enabled: true
    requests_per_second: 10
    burst_size: 20

  # CORS Configuration
  cors:
    enabled: true
    allowed_origins:
      - "https://trusted-domain.com"
    allowed_methods:
      - "GET"
      - "POST"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
    max_age: 3600

logging:
  level: "info"
  format: "json"
  output: "stdout"
  request_logging: true
  include_trace_id: true

      
#  - name: "prometheus-metrics"
#    path: "./plugins/metrics/prometheus"