version: '3.8'

services:
  iket:
    build: .
    container_name: iket
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ["/app/iket", "--config", "/app/config/config.yaml", "--routes", "/app/config/routes.yaml"]
    environment:
      - LOG_LEVEL=info
      - TZ=UTC
    volumes:
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
