version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=chat_password
      - POSTGRES_DB=chat_db
    volumes:
      - chat-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chat-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispass
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network

  keycloak_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
    volumes:
      - chat-keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
      - KC_HOSTNAME=localhost
      - KC_HTTP_RELATIVE_PATH=/auth
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8180:8080"
    depends_on:
      - keycloak_db

volumes:
  chat-postgres-data:
  redis-data:
  chat-keycloak_data:

networks:
  chat-network:
    driver: bridge