version: 1
services:
  - name: "Identity Service"
    description: "Identity & registration services"
    host: "http://host.docker.internal:7101"
    tags: ["public", "auth"]
    group: "miku"
    routes:
      - path: "/id/{rest:.*}"
        methods: ["GET"]
        name: "Auth Test"
        description: "Test authentication endpoint"
        tags: ["public"]
        priority: 1
        requireAuth: false
        stripPath: true
        enabled: true
        backend:
          - url_pattern: "/api/{rest:.*}"

  - name: "Product Service"
    description: "Product services."
    host: "http://localhost:7105"
    tags: ["public"]
    group: "miku"
    routes:
      - path: "/api/product/{rest:.*}"
        methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        requireAuth: false
        stripPath: false
        enabled: true
        backend:
          - url_pattern: "/api/{rest:.*}"



