
routes:
  - path: "/api/users/{id}"
    destination: "http://user-service:8000/users/{id}"
    methods: ["GET", "PUT", "DELETE"]
  
  - path: "/api/products"
    destination: "http://product-service:8001/products"
    methods: ["GET", "POST"]
    
  - path: "/api/orders"
    destination: "http://order-service:8002/orders"
    methods: ["GET", "POST", "PUT"]
    
  - path: "/api/auth"
    destination: "http://auth-service:8003/auth"
    methods: ["POST"]
  - path: "/index.html"
    destination: "http://localhost:8082"
    methods: ["GET", "POST"]
